### ISSUE TITLE
Lambda fix from simple email

### ISSUE THREAD

**Issue by antonioortegajr** [KadonDEngle/idxInternshipApril2018#16]
I tested and added ["body-json"] to the event.

Example:
`function sendEmail (event, done) {
    var params = {
        Destination: {
            ToAddresses: [
                RECEIVER
            ]
        },
        Message: {
            Body: {
                Text: {
                    Data: 'Name: ' + event["body-json"].name + '\nEmail: ' + event["body-json"].email + '\nDesc: ' + event["body-json"].description,
                    Charset: 'UTF-8'
                }
            },
            Subject: {
                Data: 'Website Referral Form: ' + event["body-json"].name,
                Charset: 'UTF-8'
            }
        },
        Source: SENDER
    }
    ses.sendEmail(params, done)
}`

**Comment by KadonDEngle** [comment]
Implemented Fix
